spring.application.name=TODO
spring.h2.console.enabled=true
spring.datasource.password=
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=Altynbek
spring.jpa.hibernate.ddl-auto=create
server.port=8084
